[package]
name = "console_test"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "24.0"
pollster = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]