[package]
name = "test_app"
version = "0.1.0"
edition = "2024"
include = ["shader.wgsl"]

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "^0.10"
log = "^0.4"
wgpu = { version = "^24", features = ["dx12", "metal"] } # not sure how to add vulkan to this ...
pollster = "^0.3"
bytemuck = { version = "1.16", features = [ "derive" ] }

[lib]
crate-type = ["cdylib", "rlib"]
