[package]
name = "test_app"
version = "0.1.0"
edition = "2024"
# include = ["shader.wgsl"]

[dependencies]
# core lib for events and orhet utility stuff
winit = { version = "^0.29", features = ["rwh_05"] }
# core lib used to make windows and display stuff on them
wgpu = { version = "^24", features = ["dx12", "metal"] } # not sure how to add vulkan to this ...
# advanced lib for math and extra complex stuff
bytemuck = { version = "1.16", features = [ "derive" ] }
# pretty logging
log = "^0.4"
# pretty errors
env_logger = "^0.10"
#just the basic math : 3d points vectors rotation etc...
cgmath = "^0.18"
#tobj = { version = "3.2", default-features = false, features = ["async"]}

[profile.dev]
incremental = true

[profile.release]
incremental = true

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[lib]
crate-type = ["cdylib", "rlib"]
