[package]
name = "test_app"
version = "0.1.0"
edition = "2024"
# include = ["shader.wgsl"]

[dependencies]
# core lib for events and orhet utility stuff
winit = { version = "^0.29", features = ["rwh_05"] }
# core lib used to make windows and display stuff on them
wgpu = { version = "^24", features = ["dx12", "metal"] } # not sure how to add vulkan to this ...
# advanced lib for math and extra complex stuff
bytemuck = { version = "1.16", features = [ "derive" ] }
# pretty logging
log = "^0.4"
# pretty errors
env_logger = "^0.10"
# just the basic math : 3d points vectors rotation etc...
cgmath = "^0.18"


[profile.dev]
opt-level = 1       # Light optimizations
incremental = true  # Faster recompiles
codegen-units = 16   # Parallel compilation

[profile.dev.package."*"]
opt-level = 1       # Apply to dependencies too

[profile.release]
opt-level = 3
incremental = false
codegen-units = 4   # Parallel compilation
lto = true

[profile.release.package."*"]
opt-level = 3       # Apply to dependencies too

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
